version: 0.2
env:
  variables:
    GOPRIVATE: github.com/redventures

phases:
  install:
    runtime-versions:
      golang: 1.14
    commands:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.31.0
      - ./bin/golangci-lint --version
  build:
    commands:
      - make test